#!/usr/bin/env bash

# Install latest Portainer agent on top of a Kubernetes installation (see k8s script)
# Must run with sudo privileges

set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

error() {
  echo -e "${BIRed}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

printSection "Installing Kubernetes via script"

curl https://anthony.portainer.io/k8s | bash

printSection "Installing Portainer agent (via manifest)"
info "Installing Portainer agent"

microk8s kubectl apply -f https://raw.githubusercontent.com/portainer/k8s/master/deploy/manifests/agent/ee/portainer-agent-k8s-nodeport.yaml

success "Portainer agent deployed"

info "Waiting for Portainer agent to be ready"

microk8s kubectl wait deployment/portainer-agent -n portainer --for condition=available --timeout=90s 

microk8s kubectl wait pods -n portainer --for condition=Ready -l app=portainer-agent --timeout 90s

success "Portainer agent is ready"

exit 0