#!/usr/bin/env bash

# Install latest Portainer BE server on top of a Kubernetes installation (see k8s script)
# Must run with sudo privileges

set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

error() {
  echo -e "${BIRed}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

printSection "Installing Kubernetes via script"

curl https://anthony.portainer.io/k8s | bash

printSection "Installing Portainer (via helm)"
info "Adding helm repo"

helm repo add portainer https://portainer.github.io/k8s/
helm repo update

info "Installing Portainer"

helm install --create-namespace -n portainer portainer portainer/portainer \
    --set enterpriseEdition.enabled=true \
    --set tls.force=true

success "Portainer deployed"

exit 0