#!/usr/bin/env bash

# Install LXD lab
# Must run with sudo privileges

version="v1.0.0"
set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

info "LXD server setup script ${version}"

printSection "Installing server tools"

apt -o DPkg::Lock::Timeout=60 update 

DEBIAN_FRONTEND=noninteractive apt -o DPkg::Lock::Timeout=60 install -yq \
  ca-certificates \
  curl \
  gnupg \
  uuid-runtime \
  lsb-release \
  nano \
  avahi-daemon

[[ $? -eq 0 ]] || errorAndExit "System package installation failed. Retry later."

success "System updated"

printSection "Installing LXD"

snap install lxd

printSection "Configuring LXD"

lxd init --minimal
lxc remote add --protocol simplestreams ubuntu-minimal https://cloud-images.ubuntu.com/minimal/releases/

success "LXD ready to be used"

exit 0