#!/usr/bin/env bash

# Install LXD lab
# Must run with sudo privileges

version="v1.0.0"
set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

info "LXD server setup script ${version}"

printSection "Installing server tools"

apt -o DPkg::Lock::Timeout=60 update 

DEBIAN_FRONTEND=noninteractive apt -o DPkg::Lock::Timeout=60 install -yq \
  curl \
  nano \
  iputils-ping \
  avahi-daemon

[[ $? -eq 0 ]] || errorAndExit "System package installation failed. Retry later."

success "System updated"

printSection "Installing LXD"

snap install lxd

info "Retrieving LXD pre-seed config"

curl https://anthony.portainer.io/lxd/lxd-preseed.yml > /tmp/lxd-preseed.yml

info "LXD init"

read -rsp "Server password: " lxd_pwd </dev/tty
read -p "Network interface used for macvlan: " lxd_nic </dev/tty

sed -i "s/@@PASSWD/${lxd_pwd}/g" /tmp/lxd-preseed.yml
sed -i "s/@@NIC/${lxd_nic}/g" /tmp/lxd-preseed.yml

lxd init --preseed < /tmp/lxd-preseed.yml

info "Importing base images"

curl https://downloads.portainer.io/alapenna-flask-docker-ub-2204-min.tar.gz > /tmp/flask-docker-ub-2204-min.tar.gz
lxc image import /tmp/flask-docker-ub-2204-min.tar.gz --alias flask-docker

success "LXD ready to be used"

exit 0