#!/usr/bin/env bash

# Install Asciinema on Ubuntu
# Must run with sudo privileges

version="v1.0.0"
set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

error() {
  echo -e "${BIRed}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

info "Terminal recording setup script ${version}"

printSection "Installing asciinema"

apt -o DPkg::Lock::Timeout=60 update 

DEBIAN_FRONTEND=noninteractive apt -o DPkg::Lock::Timeout=60 install -yq \
  asciinema

[[ $? -eq 0 ]] || errorAndExit "System package installation failed. Retry later."

success "asciinema installed"

asciinema auth

exit 0