apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: poc-sosiv-portainer
  name: api-pod
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: poc-sosiv-portainer
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: poc-sosiv-portainer
    spec:
      containers:
      - env:
        - name: SOSIVIO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: sosivio-admin-otp
        - name: PORT
          value: "8088"
        - name: SOSIVIO_USERNAME
          value: "admin"
        - name: SOSIVIO_URL
          value: "http://dashboard:8088"
        image: quay.io/sosivio/poc-sosiv-portainer:v0.0.1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/liveness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 7
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        name: poc-sosiv-portainer
        ports:
        - containerPort: 8088
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz/readiness
            port: 8088
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 3
          successThreshold: 1
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 200Mi
          requests:
            cpu: 10m
            memory: 10Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: sosivio
      serviceAccountName: sosivio
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-06T10:19:39Z"
  labels:
    app: poc-sosiv-portainer
  name: poc-api
spec:
  ports:
  - name: http
    port: 8088
    protocol: TCP
    targetPort: 8088
  selector:
    app: poc-sosiv-portainer
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}