#!/usr/bin/env bash

# Setup script for a portable lab.
# Based on a fresh install of Ubuntu 22.04 server (minimal)
# Must run with sudo privileges

version="v1.0.0"
set -e

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIYel="$ESeq"'1;93m'
BIWhi="$ESeq"'1;97m'

printSection() {
  echo -e "${BIYel}>>>> ${BIWhi}${1}${RCol}"
}

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

info "Lab server setup script ${version}"

printSection "Installing server tools"

apt -o DPkg::Lock::Timeout=60 update 

DEBIAN_FRONTEND=noninteractive apt -o DPkg::Lock::Timeout=60 install -yq \
  curl \
  nano \
  iputils-ping \
  avahi-daemon

[[ $? -eq 0 ]] || errorAndExit "System package installation failed. Retry later."

success "System updated"

printSection "Configuring LAN network config"

info "Network config will be applied at reboot"

curl https://anthony.portainer.io/portable-lab/00-installer-config.yml > /etc/netplan/00-installer-config.yml
chmod 644 /etc/netplan/00-installer-config.yml

curl https://anthony.portainer.io/portable-lab/wifi-connect > /root/wifi-connect
chmod 744 /root/wifi-connect

success "Server setup installation done."
info "Machine will reboot"

reboot
