#!/usr/bin/env bash

# Connect to WiFi from CLI script
# Must run with sudo privileges

version="v1.0.0"

# logging

ESeq="\x1b["
RCol="$ESeq"'0m'
BIRed="$ESeq"'1;91m'
BIGre="$ESeq"'1;92m'
BIWhi="$ESeq"'1;97m'

info() {
  echo -e "${BIWhi}${1}${RCol}"
}

success() {
  echo -e "${BIGre}${1}${RCol}"
}

errorAndExit() {
  echo -e "${BIRed}${1}${RCol}"
  exit 1
}

# !logging

info "WiFi connect script ${version}"

if [[ $(id -u) -ne 0 ]]; then
  errorAndExit "Please run this script with sudo privileges."
fi

info "Configuring WiFi"

read -p "WiFi SSID:"$'\n' net_ssid </dev/tty
read -p "WiFi password:"$'\n' net_password </dev/tty

mv /etc/netplan/00-installer-config-wifi.yaml /root/00-installer-config-wifi.yaml.bak
tee -a /etc/netplan/00-installer-config-wifi.yaml << END
# This is the network config written by 'subiquity'
network:
  wifis:
    wlp1s0:
      optional: true
      access-points:
        "${net_ssid}":
          password: "${net_password}"
      dhcp4: true
  version: 2
END

info "WiFi configuration written on disk"

netplan apply

success "WiFi successfully configured"

exit 0